# A config file containing dialogue messages
ashe:
  id: 'ashe-1'
  name: 'Ashe'
  messages:
    1:
      - 'This is a test message!'
  # A command that will run shortly after a message is sent. Make sure to omit the "/"
  # This command is executed by the console, use {player} placeholder to execute a command
  # that includes a player name.
  command: 'testcommand'
  # in ticks?
  command-delay: 80